/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppPropertiesRouteImport } from './routes/_app.properties'
import { Route as AppLauncherRouteImport } from './routes/_app.launcher'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppLauncherRoute = AppLauncherRouteImport.update({
  id: '/launcher',
  path: '/launcher',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employees': typeof AppEmployeesRoute
  '/launcher': typeof AppLauncherRoute
  '/properties': typeof AppPropertiesRoute
  '/roles': typeof AppRolesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees': typeof AppEmployeesRoute
  '/launcher': typeof AppLauncherRoute
  '/properties': typeof AppPropertiesRoute
  '/roles': typeof AppRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/launcher': typeof AppLauncherRoute
  '/_app/properties': typeof AppPropertiesRoute
  '/_app/roles': typeof AppRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/employees' | '/launcher' | '/properties' | '/roles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/employees' | '/launcher' | '/properties' | '/roles'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/employees'
    | '/_app/launcher'
    | '/_app/properties'
    | '/_app/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties': {
      id: '/_app/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/launcher': {
      id: '/_app/launcher'
      path: '/launcher'
      fullPath: '/launcher'
      preLoaderRoute: typeof AppLauncherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppLauncherRoute: typeof AppLauncherRoute
  AppPropertiesRoute: typeof AppPropertiesRoute
  AppRolesRoute: typeof AppRolesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEmployeesRoute: AppEmployeesRoute,
  AppLauncherRoute: AppLauncherRoute,
  AppPropertiesRoute: AppPropertiesRoute,
  AppRolesRoute: AppRolesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
